// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file auth0support.proto (package auth0support, syntax proto3)
/* eslint-disable */

import { Auth0Support } from "./auth0support_pb";

/**
 * create a new user on first login
 *
 * @generated from rpc auth0support.Auth0Support.CreateUser
 */
export const createUser = Auth0Support.method.createUser;

/**
 * Updates sources to keep them running in the background. This is called on
 * login by auth0 to give us a chance to boot up sources while the app is
 * loading.
 *
 * @generated from rpc auth0support.Auth0Support.KeepaliveSources
 */
export const keepaliveSources = Auth0Support.method.keepaliveSources;
