// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file auth0support.proto (package auth0support, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { AdminKeepaliveSourcesRequestSchema, KeepaliveSourcesResponseSchema } from "./account_pb";
import { file_account } from "./account_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth0support.proto.
 */
export const file_auth0support: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoMHN1cHBvcnQucHJvdG8SDGF1dGgwc3VwcG9ydCKcAQoWQXV0aDBDcmVhdGVVc2VyUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEg0KBWVtYWlsGAIgASgJEgwKBG5hbWUYAyABKAkSFgoOZW1haWxfdmVyaWZpZWQYBCABKAgSEgoKZmlyc3RfbmFtZRgFIAEoCRIRCglsYXN0X25hbWUYBiABKAkSFQoNY29ubmVjdGlvbl9pZBgHIAEoCSIpChdBdXRoMENyZWF0ZVVzZXJSZXNwb25zZRIOCgZvcmdfaWQYASABKAkyxwEKDEF1dGgwU3VwcG9ydBJZCgpDcmVhdGVVc2VyEiQuYXV0aDBzdXBwb3J0LkF1dGgwQ3JlYXRlVXNlclJlcXVlc3QaJS5hdXRoMHN1cHBvcnQuQXV0aDBDcmVhdGVVc2VyUmVzcG9uc2USXAoQS2VlcGFsaXZlU291cmNlcxIlLmFjY291bnQuQWRtaW5LZWVwYWxpdmVTb3VyY2VzUmVxdWVzdBohLmFjY291bnQuS2VlcGFsaXZlU291cmNlc1Jlc3BvbnNlQiRaImdpdGh1Yi5jb20vb3Zlcm1pbmR0ZWNoL3NkcC1nbztzZHBiBnByb3RvMw", [file_google_protobuf_struct, file_google_protobuf_timestamp, file_account]);

/**
 * @generated from message auth0support.Auth0CreateUserRequest
 */
export type Auth0CreateUserRequest = Message<"auth0support.Auth0CreateUserRequest"> & {
  /**
   * The Auth0 User ID
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * The user's email address
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * The user's full name. This will be split and stored as first_name and
   * last_name internally. It is provided for convenience since some social
   * providers do not provide first_name and last_name fields. If `first_name`
   * and `last_name` are provided, this field will be ignored.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Whether the user's email address has been verified
   *
   * @generated from field: bool email_verified = 4;
   */
  emailVerified: boolean;

  /**
   * The user's first name
   *
   * @generated from field: string first_name = 5;
   */
  firstName: string;

  /**
   * The user's last name
   *
   * @generated from field: string last_name = 6;
   */
  lastName: string;

  /**
   * The user's connection id
   *
   * @generated from field: string connection_id = 7;
   */
  connectionId: string;
};

/**
 * Describes the message auth0support.Auth0CreateUserRequest.
 * Use `create(Auth0CreateUserRequestSchema)` to create a new message.
 */
export const Auth0CreateUserRequestSchema: GenMessage<Auth0CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_auth0support, 0);

/**
 * @generated from message auth0support.Auth0CreateUserResponse
 */
export type Auth0CreateUserResponse = Message<"auth0support.Auth0CreateUserResponse"> & {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId: string;
};

/**
 * Describes the message auth0support.Auth0CreateUserResponse.
 * Use `create(Auth0CreateUserResponseSchema)` to create a new message.
 */
export const Auth0CreateUserResponseSchema: GenMessage<Auth0CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_auth0support, 1);

/**
 * The auth0 support service contains the endpoints used by Auth0 Actions to
 * post updates and receive additional information into Auth0.
 *
 * @generated from service auth0support.Auth0Support
 */
export const Auth0Support: GenService<{
  /**
   * create a new user on first login
   *
   * @generated from rpc auth0support.Auth0Support.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof Auth0CreateUserRequestSchema;
    output: typeof Auth0CreateUserResponseSchema;
  },
  /**
   * Updates sources to keep them running in the background. This is called on
   * login by auth0 to give us a chance to boot up sources while the app is
   * loading.
   *
   * @generated from rpc auth0support.Auth0Support.KeepaliveSources
   */
  keepaliveSources: {
    methodKind: "unary";
    input: typeof AdminKeepaliveSourcesRequestSchema;
    output: typeof KeepaliveSourcesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth0support, 0);

