// @generated by protoc-gen-connect-query v0.2.0 with parameter "target=ts,import_extension=.ts"
// @generated from file bookmarks.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import { CreateBookmarkRequest, CreateBookmarkResponse, DeleteBookmarkRequest, DeleteBookmarkResponse, GetBookmarkRequest, GetBookmarkResponse, ListBookmarkResponse, ListBookmarksRequest, UpdateBookmarkRequest, UpdateBookmarkResponse } from "./bookmarks_pb.ts";

export const typeName = "BookmarksService";

/**
 * @generated from rpc BookmarksService.ListBookmarks
 */
export const listBookmarks = createQueryService({
  service: {
    methods: {
      listBookmarks: {
        name: "ListBookmarks",
        kind: MethodKind.Unary,
        I: ListBookmarksRequest,
        O: ListBookmarkResponse,
      },
    },
    typeName: "BookmarksService",
  },
}).listBookmarks;

/**
 * @generated from rpc BookmarksService.CreateBookmark
 */
export const createBookmark = createQueryService({
  service: {
    methods: {
      createBookmark: {
        name: "CreateBookmark",
        kind: MethodKind.Unary,
        I: CreateBookmarkRequest,
        O: CreateBookmarkResponse,
      },
    },
    typeName: "BookmarksService",
  },
}).createBookmark;

/**
 * @generated from rpc BookmarksService.GetBookmark
 */
export const getBookmark = createQueryService({
  service: {
    methods: {
      getBookmark: {
        name: "GetBookmark",
        kind: MethodKind.Unary,
        I: GetBookmarkRequest,
        O: GetBookmarkResponse,
      },
    },
    typeName: "BookmarksService",
  },
}).getBookmark;

/**
 * @generated from rpc BookmarksService.UpdateBookmark
 */
export const updateBookmark = createQueryService({
  service: {
    methods: {
      updateBookmark: {
        name: "UpdateBookmark",
        kind: MethodKind.Unary,
        I: UpdateBookmarkRequest,
        O: UpdateBookmarkResponse,
      },
    },
    typeName: "BookmarksService",
  },
}).updateBookmark;

/**
 * @generated from rpc BookmarksService.DeleteBookmark
 */
export const deleteBookmark = createQueryService({
  service: {
    methods: {
      deleteBookmark: {
        name: "DeleteBookmark",
        kind: MethodKind.Unary,
        I: DeleteBookmarkRequest,
        O: DeleteBookmarkResponse,
      },
    },
    typeName: "BookmarksService",
  },
}).deleteBookmark;
