// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file cli.proto (package cli, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cli.proto.
 */
export const file_cli: GenFile = /*@__PURE__*/
  fileDesc("CgljbGkucHJvdG8SA2NsaSIfChBHZXRDb25maWdSZXF1ZXN0EgsKA2tleRgBIAEoCSIiChFHZXRDb25maWdSZXNwb25zZRINCgV2YWx1ZRgBIAEoCSIuChBTZXRDb25maWdSZXF1ZXN0EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCSITChFTZXRDb25maWdSZXNwb25zZTKLAQoNQ29uZmlnU2VydmljZRI8CglHZXRDb25maWcSFS5jbGkuR2V0Q29uZmlnUmVxdWVzdBoWLmNsaS5HZXRDb25maWdSZXNwb25zZSIAEjwKCVNldENvbmZpZxIVLmNsaS5TZXRDb25maWdSZXF1ZXN0GhYuY2xpLlNldENvbmZpZ1Jlc3BvbnNlIgBCJFoiZ2l0aHViLmNvbS9vdmVybWluZHRlY2gvc2RwLWdvO3NkcGIGcHJvdG8z");

/**
 * @generated from message cli.GetConfigRequest
 */
export type GetConfigRequest = Message<"cli.GetConfigRequest"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;
};

/**
 * Describes the message cli.GetConfigRequest.
 * Use `create(GetConfigRequestSchema)` to create a new message.
 */
export const GetConfigRequestSchema: GenMessage<GetConfigRequest> = /*@__PURE__*/
  messageDesc(file_cli, 0);

/**
 * @generated from message cli.GetConfigResponse
 */
export type GetConfigResponse = Message<"cli.GetConfigResponse"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message cli.GetConfigResponse.
 * Use `create(GetConfigResponseSchema)` to create a new message.
 */
export const GetConfigResponseSchema: GenMessage<GetConfigResponse> = /*@__PURE__*/
  messageDesc(file_cli, 1);

/**
 * @generated from message cli.SetConfigRequest
 */
export type SetConfigRequest = Message<"cli.SetConfigRequest"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message cli.SetConfigRequest.
 * Use `create(SetConfigRequestSchema)` to create a new message.
 */
export const SetConfigRequestSchema: GenMessage<SetConfigRequest> = /*@__PURE__*/
  messageDesc(file_cli, 2);

/**
 * @generated from message cli.SetConfigResponse
 */
export type SetConfigResponse = Message<"cli.SetConfigResponse"> & {
};

/**
 * Describes the message cli.SetConfigResponse.
 * Use `create(SetConfigResponseSchema)` to create a new message.
 */
export const SetConfigResponseSchema: GenMessage<SetConfigResponse> = /*@__PURE__*/
  messageDesc(file_cli, 3);

/**
 * a simple key-value store to store the config for the CLI
 *
 * @generated from service cli.ConfigService
 */
export const ConfigService: GenService<{
  /**
   * @generated from rpc cli.ConfigService.GetConfig
   */
  getConfig: {
    methodKind: "unary";
    input: typeof GetConfigRequestSchema;
    output: typeof GetConfigResponseSchema;
  },
  /**
   * @generated from rpc cli.ConfigService.SetConfig
   */
  setConfig: {
    methodKind: "unary";
    input: typeof SetConfigRequestSchema;
    output: typeof SetConfigResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_cli, 0);

