// @generated by protoc-gen-connect-query v1.3.1 with parameter "target=ts,import_extension=.ts"
// @generated from file config.proto (package cli, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { GetConfigRequest, GetConfigResponse, SetConfigRequest, SetConfigResponse } from "./config_pb.ts";

/**
 * @generated from rpc cli.ConfigService.GetConfig
 */
export const getConfig = {
  localName: "getConfig",
  name: "GetConfig",
  kind: MethodKind.Unary,
  I: GetConfigRequest,
  O: GetConfigResponse,
  service: {
    typeName: "cli.ConfigService"
  }
} as const;

/**
 * @generated from rpc cli.ConfigService.SetConfig
 */
export const setConfig = {
  localName: "setConfig",
  name: "SetConfig",
  kind: MethodKind.Unary,
  I: SetConfigRequest,
  O: SetConfigResponse,
  service: {
    typeName: "cli.ConfigService"
  }
} as const;
