// @generated by protoc-gen-connect-query v1.4.1 with parameter "target=ts,import_extension=.ts"
// @generated from file config.proto (package config, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { GetAccountConfigRequest, GetAccountConfigResponse, UpdateAccountConfigRequest, UpdateAccountConfigResponse } from "./config_pb.ts";

/**
 * Get the account config for the user's account
 *
 * @generated from rpc config.ConfigurationService.GetAccountConfig
 */
export const getAccountConfig = {
  localName: "getAccountConfig",
  name: "GetAccountConfig",
  kind: MethodKind.Unary,
  I: GetAccountConfigRequest,
  O: GetAccountConfigResponse,
  service: {
    typeName: "config.ConfigurationService"
  }
} as const;

/**
 * Update the account config for the user's account
 *
 * @generated from rpc config.ConfigurationService.UpdateAccountConfig
 */
export const updateAccountConfig = {
  localName: "updateAccountConfig",
  name: "UpdateAccountConfig",
  kind: MethodKind.Unary,
  I: UpdateAccountConfigRequest,
  O: UpdateAccountConfigResponse,
  service: {
    typeName: "config.ConfigurationService"
  }
} as const;
