// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts,import_extension=.ts"
// @generated from file gateway.proto (package gateway, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteBookmarkRequest, DeleteBookmarkResponse, ListBookmarkResponse, ListBookmarksRequest, UpdateBookmarkRequest, UpdateBookmarkResponse } from "./bookmarks_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The "REST" part of the gateway service. This contains all common request/reply-style APIs for the gateway.
 *
 * @generated from service gateway.GatewayService
 */
export const GatewayService = {
  typeName: "gateway.GatewayService",
  methods: {
    /**
     * @generated from rpc gateway.GatewayService.ListBookmarks
     */
    listBookmarks: {
      name: "ListBookmarks",
      I: ListBookmarksRequest,
      O: ListBookmarkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gateway.GatewayService.UpdateBookmark
     */
    updateBookmark: {
      name: "UpdateBookmark",
      I: UpdateBookmarkRequest,
      O: UpdateBookmarkResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc gateway.GatewayService.DeleteBookmark
     */
    deleteBookmark: {
      name: "DeleteBookmark",
      I: DeleteBookmarkRequest,
      O: DeleteBookmarkResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

