// @generated by protoc-gen-connect-query v0.6.0 with parameter "target=ts,import_extension=.ts"
// @generated from file invites.proto (package invites, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateInviteRequest, CreateInviteResponse, ListInvitesRequest, ListInvitesResponse, RevokeInviteRequest, RevokeInviteResponse } from "./invites_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";
import { createQueryService, createUnaryHooks, UnaryFunctionsWithHooks } from "@connectrpc/connect-query";

export const typeName = "invites.InviteService";

/**
 * provides all operations for inviting people to an organization
 *
 * @generated from service invites.InviteService
 */
export const InviteService = {
  typeName: "invites.InviteService",
  methods: {
    /**
     * @generated from rpc invites.InviteService.CreateInvite
     */
    createInvite: {
      name: "CreateInvite",
      I: CreateInviteRequest,
      O: CreateInviteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc invites.InviteService.ListInvites
     */
    listInvites: {
      name: "ListInvites",
      I: ListInvitesRequest,
      O: ListInvitesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc invites.InviteService.RevokeInvite
     */
    revokeInvite: {
      name: "RevokeInvite",
      I: RevokeInviteRequest,
      O: RevokeInviteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

const $queryService = createQueryService({  service: InviteService,});

/**
 * @generated from rpc invites.InviteService.CreateInvite
 */
export const createInvite: UnaryFunctionsWithHooks<CreateInviteRequest, CreateInviteResponse> = {   ...$queryService.createInvite,  ...createUnaryHooks($queryService.createInvite)};

/**
 * @generated from rpc invites.InviteService.ListInvites
 */
export const listInvites: UnaryFunctionsWithHooks<ListInvitesRequest, ListInvitesResponse> = {   ...$queryService.listInvites,  ...createUnaryHooks($queryService.listInvites)};

/**
 * @generated from rpc invites.InviteService.RevokeInvite
 */
export const revokeInvite: UnaryFunctionsWithHooks<RevokeInviteRequest, RevokeInviteResponse> = {   ...$queryService.revokeInvite,  ...createUnaryHooks($queryService.revokeInvite)};
