name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  code-quality:
    name: 'Code Quality'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ESLint
        run: pnpm lint

      - name: Prettier
        run: pnpm prettier:check

      - name: Typecheck
        run: pnpm typecheck
