name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        continue-on-error: false

      - name: ESLint
        run: npm run lint
        continue-on-error: false

      - name: Prettier
        run: npm run format:check
        continue-on-error: false

      - name: Typecheck
        run: npm run typecheck
        continue-on-error: false
