name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      # Pull the version from the tag and update the package.json
      - name: Update Version
        continue-on-error: true
        run: npm version from-git --no-git-tag-version

      - name: Publish package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version update
        continue-on-error: true
        run: |
          git config --global user.email "overmindtech@users.noreply.github.com"
          git config --global user.name "Github Actions"
          git commit -am "Version Bump" && git push

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
