name: Tests
on: push
jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16
          - 18
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node }}'
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        continue-on-error: false

      - name: Run tests
        run: npm run test
